export const courses: { [key: string]: string } = {
  BC_JAVASCRIPT: "PREP",
  BC_SALESFORCE: "SALESFORCE-PREP",
  INTRO_FRONTEND: "INTRO_FRONTEND",
  INTRO_JAVASCRIPT: "INTRO_JS_FULLSTACK",
  INTRO_JAVASCRIPT_ATR: "INTRO_JAVASCRIPT_ATR",
  BOOTCAMP_JS_CONTENT: "BC_JAVASCRIPT",
  BOOTCAMP_SF_CONTENT: "BC_SALESFORCE"
};
