#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "()=======================================================()"
echo "             *     ,MMM8&&&.            *
                  MMMM88&&&&&    .
                 MMMM88&&&&&&&
     *           MMM88&&&&&&&&
                 MMM88&&&&&&&&
                 'MMM88&&&&&&'
                   'MMM8&&&'      *
          |\___/|
          )     (             .              '
         =\     /=
           )===(       *
          /     \                            '
          |     |                            '
         /       \                 '         '
         \       /                           '
  _/\_/\_/\__  _/_/\_/\_/\_/\_/\_/\_/\_/\_/\_
  |  |  |  |( (  |  |  |  |  |  |  |  |  |  |
  |  |  |  | ) ) |  |  |  |  |  |  |  |  |  |
  |  |  |  |(_(  |  |  |  |  |  |  |  |  |  |

  "
echo "// -----------------CHECK LINTING----------------------- //"
npm run lint

echo "// -----------------CHECK BUILDING---------------------- //"
npm run build

echo "// --------------CHECK FOR NEW CHANGES------------------ //"
hasChanged=0 # 0 if no changes, 1 if changes
git diff --exit-code >/dev/null || hasChanged=1

if [ $hasChanged -eq 1 ]; then
  echo "\n⚠️  You have uncommitted changes. Please commit them before pushing.\n"
  exit 1
else 
  echo "\n✅  No uncommitted changes.\n"
fi

echo "// --------------------PUSHING-------------------------- //"